---
title: "Epid 814 - Advanced Modeling Methods"
author: "Instructor: Marisa Eisenberg"
date: "Fall 2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
---
<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
  </style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Course Syllabus 

* [Syllabus](Epid814_SyllabusF2021.pdf)

<!-- * [Readings](Readings/) -->

<!-- * [Lectures](Lectures/) -->

<!-- * [Labs](Labs/) -->

<hr>

## Course schedule
To be added after the initial topic discussion on Monday. Topics are subject to change and rearrangement! (We may also not get to all the topics listed)

<br>

##### 1. Introduction and topics discussion (Aug 30, 2021)

[List of potential topics to cover in the course - please feel free to add! We will discuss on Monday](https://docs.google.com/spreadsheets/d/1-vmib4ApYCiLnRk9hxL5HltT4W-hrvrIUlfCAs9uZJ4/edit#gid=0)

<br>

##### 2. Parameter estimation and maximum likelihood  (Sep 1, 2021 & Sep 8, 2021)

- Maximum likelihood with mathematical models - [Lecture](Lectures/ParameterEstimationML.pdf)

- Parameter estimation coding session - [Lab](Labs/EstimationLab/)

- [Model vs. code comparison](Labs/EstimationLab/ModelNotes.pdf)

<br>

##### Journal Club (Sep 13, 2021)

- [Dissecting racial bias in an algorithm used to manage the health of populations](https://www.science.org/doi/abs/10.1126/science.aax2342)
- Reminder to add papers and sign up to lead a journal club [here](https://docs.google.com/spreadsheets/d/1-vmib4ApYCiLnRk9hxL5HltT4W-hrvrIUlfCAs9uZJ4/edit#gid=1663288766)

<br>

##### 3. Uncertainty and identifiability

- Identifiability and parameter uncertainty - [Lecture](Lectures/IdentifiabilityUncertainty.pdf) 

- [Useful post on Wald/FIM vs. Likelihood-based confidence intervals](https://thestatsgeek.com/2014/02/08/wald-vs-likelihood-ratio-test/)

- [Identifiability and uncertainty Lab](Labs/IdentifiabilityUncertainty/IdentifiablilityUncertaintyLab.html) 

<br>


##### 4. Intro to MCMC & Bayesian approaches

- Intro to Bayesian Approaches to Parameter Estimation, MCMC - [Lecture](Lectures/BayesianEstimation.pdf) 

- [Lab - Metropolis Sampler](Labs/MetropolisSampler/MetropolisSampler.html)

- [BayesianTools Lab](Labs/BayesianToolsLab/BayesianTools.html) 
    - [Example code from class](Labs/BayesianToolsLab/In-class-BayesianTools.R)

<br>

##### Journal Club (Oct 4, 2021)

- This week we're discussing two recent papers by Jon Zelner's group!
- [There are no equal opportunity infectors: Epidemiological modelers must rethink our approach to inequality in infection risk](https://arxiv.org/abs/2109.00580) (Kelly discussion lead)
- [Accounting for Uncertainty During a Pandemic](http://www.stat.columbia.edu/~gelman/research/published/UncertaintyPandemic.pdf)
- Reminder to add papers and sign up to lead a journal club [here](https://docs.google.com/spreadsheets/d/1-vmib4ApYCiLnRk9hxL5HltT4W-hrvrIUlfCAs9uZJ4/edit#gid=1663288766)

<br>

##### 5. Data-scraping and data-wrangling 
(moved this up since it might be useful for making data sets we can play with for the ML and networks sections below)

- Using R to pull data using API's - Twitter, Facebook, and Google Maps

- Collecting and working with twitter data

- [Twitter data collection lab](Labs/DataScrapingPart1-Twitter/DataScraping-Twitter.html)
    - [Rtweet code](Labs/DataScrapingPart1-Twitter/rtweetexample.R)
    - [Webpage scraping code](https://gist.github.com/marisae/2f506e9c2f768303abf3d34c215555b1)

- Additional useful tutorials/code
    - [Tutorial](https://alexluscombe.ca/post/r-pdftools/) for reading text from pdfs into R using the [pdftools package](https://cran.r-project.org/web/packages/pdftools/pdftools.pdf)
    - [Followup tutorial](https://alexluscombe.ca/blog/parsing-your-.pdfs-in-r/) on parsing the data with regular expressions
    - Two tutorials on extracting table data from pdfs using the [tabulizer](https://cran.r-project.org/web/packages/tabulizer/vignettes/tabulizer.html) package: [tutorial 1](https://datascienceplus.com/extracting-tables-from-pdfs-in-r-using-the-tabulizer-package/), [tutorial 2](https://medium.com/@ketanrd.009/how-to-extract-pdf-tables-in-r-e994c0fe4e28)
    - [CronR package](https://cran.r-project.org/web/packages/cronR/cronR.pdf) for scheduling scripts (we can show some examples of this as well in class if people are interested)

- An [interesting article](https://howwegettonext.com/scientists-like-me-are-studying-your-tweets-are-you-ok-with-that-c2cfdfebf135) about the ethics of using public data and our perception of privacy

<br>

##### Journal Club (Oct 13, 2021)

- [A Bayesian Workflow for Parameter Estimation](https://arxiv.org/pdf/2011.01808.pdf) (Hannah discussion lead)

- Reminder to add papers and sign up to lead a journal club [here](https://docs.google.com/spreadsheets/d/1-vmib4ApYCiLnRk9hxL5HltT4W-hrvrIUlfCAs9uZJ4/edit#gid=1663288766)

<br>


##### 6. Sampling-based approaches to global sensitivity analysis

- Latin hypercube and Sobol sampling, local and global sensitivity methods

- [Lecture Slides](Lectures/SensitivityandSampling.pdf)

- [Example code](Labs/SamplingSensitivity.R)

- Interesting paper on Sobol vs. LHS: [To Sobol or not to Sobol? The effects of sampling schemes in systems biology applications](https://www.sciencedirect.com/science/article/pii/S0025556421000419)

- Journal club paper: [Marino et al. "A methodology for performing global uncertainty and sensitivity analysis in systems biology." Journal of theoretical biology 254.1 (2008): 178-196.](https://www.sciencedirect.com/science/article/pii/S0022519308001896)

- Potentially for later: active subspace methods, surrogate models

<br>

##### Journal Club (Oct 25, 2021 and Oct 27, 2021)

- Journal club paper: [Marino et al. "A methodology for performing global uncertainty and sensitivity analysis in systems biology." Journal of theoretical biology 254.1 (2008): 178-196.](https://www.sciencedirect.com/science/article/pii/S0022519308001896)

- Oct 27: Discuss the ABMs portion of the paper, and try out some of the methods together

- This R package includes the eFAST method described in the journal club paper, plus a ton more: https://cran.r-project.org/web/packages/sensitivity/index.html

- And this package computes Sobol/variance-based sensitivity analyses:https://cran.r-project.org/web/packages/sensobol/vignettes/sensobol.pdf

- Reminder to add papers and sign up to lead a journal club [here](https://docs.google.com/spreadsheets/d/1-vmib4ApYCiLnRk9hxL5HltT4W-hrvrIUlfCAs9uZJ4/edit#gid=1663288766)

<br>


##### 7. Basic intro to some useful algorithms/machine learning methods
<!-- - Overall topics of interest: k-means clustering, support vector machines, singular value decomposition (possibly a little linear algebra review also?), basic neural networks -->
- [Clustering Methods Lecture](Lectures/Clustering.pdf)
    - Density-sensitive version of DBSCAN: [OPTICS](https://en.wikipedia.org/wiki/OPTICS_algorithm)
    - [Another overview of DBSCAN and some of its variants](https://cran.r-project.org/web/packages/dbscan/vignettes/dbscan.pdf)
- [Clustering Lab](Labs/clustering.R)
    - Other useful tutorials:
        - [Cluster analysis in R](https://rstudio-pubs-static.s3.amazonaws.com/33876_1d7794d9a86647ca90c4f182df93f0e8.html)
        - [Clustering in R Overview](https://www.datanovia.com/en/blog/types-of-clustering-methods-overview-and-quick-start-r-code/)
- [Brainstorming twitter data collection ideas](https://docs.google.com/document/d/1V9q25Xtmm4_SryTeR5xgHX3cVmR3_O7R0y93wYxe_Q4/edit)
- [Classification]<!-- (Lectures/Classification.pdf) -->
- [Lab: Naive Bayes classification with twitter data]<!-- (Labs/ClassifierLab/TwitterNaiveBayes.html)-->
    <!-- - Twitter topic datasets: [Aliens](Labs/ClassifierLab/AliensTwitterData.Rdata), [Vaccines](Labs/ClassifierLab/vaccines.Rdata), [Vaccines 2](Labs/ClassifierLab/vaccines171119.Rdata) -->
    - Other useful tutorials on Naive Bayes
        - [Naive Bayes in R for movie reviews](https://rpubs.com/cen0te/naivebayes-sentimentpolarity)
        - [Naive Bayes with Titanic survivorship](https://www.r-bloggers.com/understanding-naive-bayes-classifier-using-r/)
        - [Naive Bayes Overview](https://uc-r.github.io/naive_bayes) - includes more details on cross validation, confusion matrices, Laplace smoother, etc.


<br>


##### 8. Reproduction number - data driven approaches to $\mathcal{R}_0$ and $\mathcal{R}_t$

- Quick recap: what are $\mathcal{R}_0$ and $\mathcal{R}_t$?

- Serial interval approaches to calculating $\mathcal{R}_t$

- Possible journal club with Royal Society review paper

<br>

##### 9. Reproduction number - next generation matrix approaches

- The next generation matrix and thinking about the linear algebra of the next generation matrix

- Maybe: type and target reproduction numbers, stochastic $\mathcal{R}_0$, $\mathcal{R}_0$ for networks

<br>


##### 10. Time series analysis intro

<br>

##### 11. Visualization with ggplot2

- Intro to ggplot and collection of examples <!-- : [Lab - our collection of ggplot examples](Labs/ggplotExamples/BasicExamples.html), [Dataset](Labs/ggplotExamples/Datasets/YemenCholeraOutbreak.csv) -->

- [ggrepel example](Labs/ggplotExamples/ggRepelExample.html)

- [Nice ggplot tutorial](http://r-statistics.co/ggplot2-Tutorial-With-R.html)

- [Another tutorial](http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/)

- [Mapping with ggplot](http://zevross.com/blog/2014/07/16/mapping-in-r-using-the-ggplot2-package/)

- [ggdag & dagitty](https://cran.r-project.org/web/packages/ggdag/vignettes/intro-to-ggdag.html)

<br>

##### 12. Other topics to cover if time!

- Parallelizing code in R (maybe combine with another topic since we can do an example fairly quickly)

- Shiny apps and interactives

- Bootstrapping

- Methods for stochastic models

- Compartmental models and DAGs

- And other stuff---topological data analysis, Kullback-Liebler divergence

<!--

##### 9. Network analysis and network modeling
- [Networks lecture](Lectures/Networks.pdf)
    - Review of network concepts (centrality, modularity, etc.)
    - Network simulation methods (Barabasi-Albert, Erdos-Renyi, etc.)
    - Configuration models
- Network data sets
    - [Mark Newman’s list of data sets](http://www-personal.umich.edu/~mejn/netdata/)
    - [UC Irvine Network Data Repository](https://networkdata.ics.uci.edu/)
    - [Facebook social network data from kaggle](https://www.kaggle.com/c/FacebookRecruiting/data)
    - [Colorado network data set](https://icon.colorado.edu/#!/about)
    - [Transitland](https://transit.land): transit data for major cities and visualization packages for it: [transitland github](https://github.com/transitland/transitland-processing-animation), [visualizations 1](https://vimeopro.com/willgeary/transit-flows), [more visualizations](https://mapzen.com/blog/animating-transitland/)


<br>

##### 10. Stochastic models
- Ideas, Markov models
- Gillespie algorithm
- Tau-leaping
- Possibly discuss hybrid models, journal club some of [Linda Allen's book](https://www.amazon.com/Introduction-Stochastic-Processes-Applications-Biology-ebook/dp/B005H6YSNM)

<br>

##### 11. Additional Topics
- Game theory and modeling behavior
- Spatial statistics and spatial/spatiotemporal clustering
- Analysis/wrangling of text data
- Optimization algorithms
- Agent-based modeling
-->

<br>


## Journal club topics

- [Dissecting racial bias in an algorithm used to manage the health of populations](https://www.science.org/doi/abs/10.1126/science.aax2342)

<br>


## Useful Links
- [EECS 545 (Machine Learning)](https://ece.engin.umich.edu/academics/course-information/course-descriptions/eecs-545/) - online course with a good overview of machine learning approaches

<br><br><br>
